from ecologits.electricity_mix_repository import electricity_mixes
from ecologits.model_repository import Providers, models
from ecologits.tracers.utils import llm_impacts
from fastapi import APIRouter, Body, HTTPException

from app.api.v1beta.responses import (
    ELECTRICITY_MIX_RESPONSES,
    ESTIMATIONS_RESPONSES,
    MODELS_RESPONSES,
    PROVIDERS_RESPONSES,
)

api_router_v1beta = APIRouter(prefix="/v1beta")


@api_router_v1beta.get(
    "/providers",
    response_model=dict,
    tags=["Catalog"],
    summary="List all supported providers",
    responses=PROVIDERS_RESPONSES,
)
def get_providers():
    try:
        providers_list = [provider.value for provider in Providers]
        return {
            "providers": providers_list,
        }
    except Exception:
        raise HTTPException(status_code=500, detail="Failed to retrieve providers")


@api_router_v1beta.get(
    "/models/{provider_name}",
    response_model=dict,
    tags=["Catalog"],
    summary="List models for a provider",
    description=(
        "Models may include **warning** and **error** indicators "
        "([details](https://ecologits.ai/latest/tutorial/warnings_and_errors/))."
    ),
    responses=MODELS_RESPONSES,
)
def get_models(provider_name: str):
    try:
        provider = Providers[provider_name]
    except KeyError:
        raise HTTPException(status_code=404, detail="Provider not found")

    try:
        filter_model = []
        for model in models.list_models():
            if model.provider == provider:
                filter_model.append(model)
        return {
            "models": filter_model,
        }
    except Exception:
        raise HTTPException(status_code=500, detail="Failed to retrieve models")


@api_router_v1beta.get(
    "/electricity-mix-zones/{zone}",
    response_model=dict,
    tags=["Electricity mix"],
    summary="Get electricity mix for a zone",
    description=(
        "Use ISO 3166-1 alpha-3 codes (`USA`, `FRA`, `DEU`) "
        "(or `WOR` for World average)."
    ),
    responses=ELECTRICITY_MIX_RESPONSES,
)
def get_electricity_mix_zones(zone: str):
    try:
        electricity_mix = electricity_mixes.find_electricity_mix(zone)
    except Exception:
        raise HTTPException(
            status_code=500, detail="Failed to retrieve electricity mix zone"
        )

    if electricity_mix is None:
        raise HTTPException(
            status_code=404,
            detail=f"Electricity mix zone '{zone}' is not supported by EcoLogits",
        )

    return {"electricity_mix": electricity_mix}


@api_router_v1beta.post(
    "/estimations",
    response_model=dict,
    tags=["Estimations"],
    summary="Estimate environmental impacts of an LLM request",
    responses=ESTIMATIONS_RESPONSES,
)
def post_estimations(
    provider: str = Body(
        ...,
        embed=True,
        examples=["openai"],
        description="Provider identifier (use `GET /v1beta/providers` to list valid values).",
    ),
    model_name: str = Body(
        ...,
        embed=True,
        examples=["gpt-4o-mini"],
        description="Model identifier as registered in EcoLogits (use `GET /v1beta/models/{provider}` to list valid values).",
    ),
    output_token_count: int = Body(
        ...,
        embed=True,
        examples=[300],
        description="Number of tokens generated by the model.",
    ),
    request_latency: float = Body(
        ...,
        embed=True,
        examples=[1.5],
        description="Measured request latency in seconds.",
    ),
    electricity_mix_zone: str | None = Body(
        default=None,
        embed=True,
        examples=["WOR"],
        description="ISO 3166-1 alpha-3 zone code for the electricity mix. Defaults to `WOR` (world average). (use `GET /v1beta/electricity-mix-zones/{zone}` to check zone availability)",
    ),
):
    try:
        impacts = llm_impacts(
            provider=provider,
            model_name=model_name,
            output_token_count=output_token_count,
            request_latency=request_latency,
            electricity_mix_zone=electricity_mix_zone,
        )
        return {"impacts": impacts}

    except Exception:
        raise HTTPException(status_code=500, detail="Failed to Estimate impacts")
