from ecologits.electricity_mix_repository import electricity_mixes
from ecologits.model_repository import Providers, models
from ecologits.tracers.utils import llm_impacts
from fastapi import APIRouter, Body, HTTPException

from app.api.v1beta.responses import (
    ELECTRICITY_MIX_RESPONSES,
    ESTIMATIONS_RESPONSES,
    MODELS_RESPONSES,
    PROVIDERS_RESPONSES,
)

api_router_v1beta = APIRouter(prefix="/v1beta")


@api_router_v1beta.get(
    "/providers",
    response_model=dict,
    tags=["Catalog"],
    summary="List all supported providers",
    responses=PROVIDERS_RESPONSES,
)
def get_providers():
    try:
        providers_list = [provider.value for provider in Providers]
        return {
            "providers": providers_list,
        }
    except Exception:
        raise HTTPException(status_code=500, detail="Failed to retrieve providers")


@api_router_v1beta.get(
    "/models/{provider_name}",
    response_model=dict,
    tags=["Catalog"],
    summary="List models for a provider",
    description=(
        "Models may include **warning** and **error** indicators "
        "([details](https://ecologits.ai/latest/tutorial/warnings_and_errors/))."
    ),
    responses=MODELS_RESPONSES,
)
def get_models(provider_name: str):
    try:
        provider = Providers[provider_name]
    except KeyError:
        raise HTTPException(status_code=404, detail="Provider not found")

    try:
        filter_model = []
        for model in models.list_models():
            if model.provider == provider:
                filter_model.append(model)
        return {
            "models": filter_model,
        }
    except Exception:
        raise HTTPException(status_code=500, detail="Failed to retrieve models")


@api_router_v1beta.get(
    "/electricity-mix-zones/{zone}",
    response_model=dict,
    tags=["Electricity mix"],
    summary="Get electricity mix for a zone",
    description=(
        "Use ISO 3166-1 alpha-3 codes (`USA`, `FRA`, `DEU`) "
        "(or `WOR` for World average)."
    ),
    responses=ELECTRICITY_MIX_RESPONSES,
)
def get_electricity_mix_zones(zone: str):
    try:
        electricity_mix = electricity_mixes.find_electricity_mix(zone)
    except Exception:
        raise HTTPException(
            status_code=500, detail="Failed to retrieve electricity mix zone"
        )

    if electricity_mix is None:
        raise HTTPException(
            status_code=404,
            detail=f"Electricity mix zone '{zone}' is not supported by EcoLogits",
        )

    return {"electricity_mix": electricity_mix}


@api_router_v1beta.post(
    "/estimations",
    response_model=dict,
    tags=["Estimations"],
    summary="Estimate environmental impacts of an LLM request",
    responses=ESTIMATIONS_RESPONSES,
)
def post_estimations(
    provider: str = Body(
        ...,
        embed=True,
        examples=["openai"],
        description="Provider identifier (use `GET /v1beta/providers` to list valid values).",
    ),
    model_name: str = Body(
        ...,
        embed=True,
        examples=["gpt-4o-mini"],
        description="Model identifier as registered in EcoLogits (use `GET /v1beta/models/{provider}` to list valid values).",
    ),
    output_token_count: int = Body(
        ...,
        embed=True,
        examples=[300],
        description="Number of tokens generated by the model.",
    ),
    request_latency: float | None = Body(
        default=None,
        embed=True,
        examples=[1.5],
        description="Measured request latency in seconds.",
    ),
    electricity_mix_zone: str | None = Body(
        default=None,
        embed=True,
        examples=["WOR"],
        description="ISO 3166-1 alpha-3 zone code for the electricity mix. Defaults to `WOR` (world average). (use `GET /v1beta/electricity-mix-zones/{zone}` to check zone availability)",
    ),
):
    try:
        impacts = llm_impacts(
            provider=provider,
            model_name=model_name,
            output_token_count=output_token_count,
            # Use high request latency if not provided, to default the latency estimation made with
            # the TPS and TTFT data from OpenRouter.
            # TODO: remove the high value when the estimations module in EcoLogits (Python) is ready
            request_latency=request_latency if request_latency is not None else 1e6,
            electricity_mix_zone=electricity_mix_zone,
        )
        return {"impacts": impacts}

    except Exception:
        raise HTTPException(status_code=500, detail="Failed to Estimate impacts")
@api_router_v1beta.post(
    "/expert-estimations",
    response_model=dict,
    tags=["Estimations"],
    summary="Estimate environmental impacts of an LLM request on unsupported models or custom deployements.",
    responses=ESTIMATIONS_RESPONSES,
)
def post_expert_estimations(
    output_token_count: int = Body(
        ...,
        embed=True,
        examples=[300],
        description="Number of tokens generated by the model.",
    ),
    model_active_params: float = Body(
        ...,
        embed=True,
        examples=[88],
        description="Number of active parameters of the model (in billion).",
    ),
    model_total_params: float = Body(
        ...,
        embed=True,
        examples=[440],
        description="Number of total parameters of the model (in billion).",
    ),
    request_latency: float | None = Body(
        default=None,
        embed=True,
        examples=[1.56],
        description="Measured request latency in seconds.",
    ),
    tps: float | None = Body(
        default=None,
        embed=True,
        examples=[58],
        description="Number of tokens generated per second by the model.",
    ),
    ttft: float | None = Body(
        default=None,
        embed=True,
        examples=[1.63],
        description="Time-to-first-token latency in seconds.",
    ),
    datacenter_pue: float | None = Body(
        default=None,
        embed=True,
        examples=[1.2],
        description="Power Usage Effectiveness of the data center.",
    ),
    datacenter_wue: float | None = Body(
        default=None,
        embed=True,
        examples=[0.6],
        description="Water Usage Effectiveness of the data center in L/kWh.",
    ),
    electricity_mix_adpe: float = Body(
        default=1.349e-8,
        embed=True,
        examples=[1.349e-8],
        description="ADPe impact factor of electricity consumption of kgSbeq / kWh (Antimony). (use `GET /v1beta/electricity-mix-zones/{zone}` to get values. Default: world)",
    ),
    electricity_mix_pe: float = Body(
        default=2.5871,
        embed=True,
        examples=[2.5871],
        description="PE impact factor of electricity consumption in MJ / kWh. (use `GET /v1beta/electricity-mix-zones/{zone}` to get values. Default: world)",
    ),
    electricity_mix_gwp: float = Body(
        default=0.45829,
        embed=True,
        examples=[0.45829],
        description="GWP impact factor of electricity consumption in kgCO2eq / kWh. (use `GET /v1beta/electricity-mix-zones/{zone}` to get values. Default: world)",
    ),
    electricity_mix_wue: float = Body(
        default=3.908,
        embed=True,
        examples=[3.908],
        description="WCF impact factor of electricity consumption in L / kWh. (use `GET /v1beta/electricity-mix-zones/{zone}` to get values. Default: world)",
    )
):
    try:
        impacts = compute_llm_impacts(
            output_token_count=output_token_count,
            model_active_parameter_count= model_active_params,
            model_total_parameter_count = model_total_params,
            # TODO: remove the high value when the estimations module in EcoLogits (Python) is ready
            request_latency = request_latency if request_latency is not None else 1e6,
            tps = tps,
            ttft = ttft,
            datacenter_pue = datacenter_pue,
            datacenter_wue = datacenter_wue,
            if_electricity_mix_adpe = electricity_mix_adpe,
            if_electricity_mix_pe = electricity_mix_pe,
            if_electricity_mix_gwp = electricity_mix_gwp,
            if_electricity_mix_wue = electricity_mix_wue,
        )
        return {"impacts": impacts}

    except Exception:
        raise HTTPException(status_code=500, detail=f"Failed to Estimate impacts")
