name: Deploy to Clever Cloud

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Clever Tools CLI
        run: |
          CC_VERSION=latest
          curl -s -O https://clever-tools.clever-cloud.com/releases/${CC_VERSION}/clever-tools-${CC_VERSION}_linux.tar.gz
          tar -xvf clever-tools-${CC_VERSION}_linux.tar.gz
          PATH=${PATH}:$(pwd)/clever-tools-${CC_VERSION}_linux

      - name: Login to Clever Cloud
        run: ./clever-tools-latest_linux/clever login --token ${{ secrets.CLEVER_TOKEN }} --secret ${{ secrets.CLEVER_SECRET }}

      - name: Deploy API to Clever Cloud
        run: |
          ./clever-tools-latest_linux/clever link $CLEVER_APP_ID
          ./clever-tools-latest_linux/clever deploy -f
